### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Hanna432** [VirtualAkseli/ot-harjoitustyo#1]
Koodi ladattu 23.4.2019 klo 14.53

- Perustoiminnallisuudet toimivat oikein.
- Jako eri luokkiin on hyvä ja pakkausrakenne on järkevä. Ohjelma koostuu vain kolmesta luokasta mutta tässä tapauksessa se riittää ja enemmän luokkia ei sinänsä parantaisi ohjelman laatua.
- Koodi on selkeä siinä mielessä että on helppo ymmärtää miten ohjelma suurin piirtein toimii, mutta ykstitysikohdat voivat olla aika monimutkaisia.
- Metodit ovat nimetty selkeästi ja myös muuttujien nimet ovat useimmiten järkeviä.
- UI:ssa on käytössä kolme eri taulukkoa: table, idArr ja initTable. On mahdollista että tähän on joku hyvä syy joka en näe, mutta luulen että olisi mahdollista käyttää taulukko table initTable:in sijaan ja postaa initTable kokonaan. Näin koodi tulisi vähän selkeämpi.
- Sudoku-luokassa on paljon muuttujia jotka eivät tällä hetkellä ole käytössä (error, txt, base, idArr, id, badInt) ja jos et aijo käyttää niitä niin ne voidaan poistaa. Myös UI:ssa on ylimääräisiä muuttujia.
- Virheilmoitus duplikaattinumeroista ei aina toimii oikein. Jos kirjoitan numero joka on oikein, poistan numeron ja kirjoitan sen uudestaan samaan ruutuun niin tulee virheilmoitus. Myös jos laitan virheellisen numeron ruutuun ja en poista sitä ja sitten laitan sallittu numero jonkun toiseen ruutuun niin virheilmotus katoaa vaikka virhe on vielä olemassa.

**Comment by VirtualAkseli** [comment]
Kiitos ajatuksella tehdystä koodikatselmoinnista!
Olin tietoinen tuosta viimeisestä mainitsemastasi asiasta ja korjaan sen jos keksin keinon.
Hyvä, että koodini ei ollut turhan työlästä lukea.
